### ISSUE TITLE
console is undefined in IE9

### ISSUE THREAD

**Issue by rymohr** [jeffsu/mochiscript#2]
It only happens when the developer tools have not been enabled and the console is unavailable.

This appears to be the offending block of code, although I noticed a number of unchecked `console.log` calls throughout the code:

```
# mochiscript.js
(function (window) {
var $m  = {
  ROOT: window,
  ADAPTER: {
    out:  console.log,
    outs: console.log,
  },
  PLATFORM: 'browser'
};
```

**Comment by jeffsu** [comment]
Good find.

Fixed, hope this works because I don't have IE9 to test it (version 0.4.6-pre3).  Thanks!

**Comment by rymohr** [comment]
Same here.  I had to jump through hoops to get a test copy installed via
virtualbox on my mac.  These instructions came in handy if you ever need to
do the same:
http://developmentstickies.wordpress.com/2011/08/19/run-microsoft-ie9-on-windows7-vhd-image-in-virtualbox-for-free/

Great library by the way!  Much prefer it over the fancier javascript
alternatives like coffeescript.

**Comment by jeffsu** [comment]
Thanks!  I'm glad people are using it.  We've been using it at Factual for
4 years now.

-Jeff

On Tue, Feb 28, 2012 at 5:34 PM, Ryan Mohr <
reply@reply.github.com
